# Generated by Django 6.0.3 on 2026-07-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Transportation', 'Transportation'), ('Tour Guide', 'Tour Guide'), ('Travel Agency', 'Travel Agency'), ('Activity Provider', 'Activity Provider'), ('Homestay', 'Homestay'), ('Camping', 'Camping'), ('Adventure Sports', 'Adventure Sports'), ('Taxi Service', 'Taxi Service')], max_length=50)),
                ('business_name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_provider_requests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tourist', 'Tourist'), ('service_provider', 'Service Provider')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Transportation', 'Transportation'), ('Tour Guide', 'Tour Guide'), ('Travel Agency', 'Travel Agency'), ('Activity Provider', 'Activity Provider'), ('Homestay', 'Homestay'), ('Camping', 'Camping'), ('Adventure Sports', 'Adventure Sports'), ('Taxi Service', 'Taxi Service')], max_length=50)),
                ('business_name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_details', to='tourism.user')),
            ],
            options={
                'db_table': 'service_providers',
            },
        ),
    ]
