# Generated by Django 6.0.3 on 2026-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_serviceproviderrequest_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('Waterfall', 'Waterfall'), ('Temple', 'Temple'), ('Wildlife', 'Wildlife'), ('Museum', 'Museum'), ('Other', 'Other')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
    ]
