# Generated by Django 6.0.3 on 2026-08-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
