# Generated by Django 6.0.3 on 2026-08-13 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_hotel_hotelfacility_hotelimage_room_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='tourism.destination'),
        ),
    ]
