# Generated by Django 6.0.3 on 2026-08-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_serviceprovider_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='tourist_profiles/')),
                ('travel_preferences', models.JSONField(blank=True, default=list)),
                ('travel_style', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to='tourism.user')),
            ],
        ),
    ]
