# Generated by Django 6.0.3 on 2026-08-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_touristprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('Hotel', 'Hotel Owner'), ('Restaurant', 'Restaurant Owner'), ('Transportation', 'Transportation Owner'), ('Activity', 'Activity Owner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceproviderrequest',
            name='service_type',
            field=models.CharField(choices=[('Hotel', 'Hotel Owner'), ('Restaurant', 'Restaurant Owner'), ('Transportation', 'Transportation Owner'), ('Activity', 'Activity Owner')], max_length=50),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('available_times', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tourism.serviceprovider')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='activities/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.activity')),
            ],
            options={
                'db_table': 'activity_images',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cuisine_type', models.CharField(max_length=150)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='tourism.serviceprovider')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFacility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='tourism.restaurant')),
            ],
            options={
                'db_table': 'restaurant_facilities',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.restaurant')),
            ],
            options={
                'db_table': 'restaurant_images',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('transportation_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_location', models.CharField(max_length=255)),
                ('service_area', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('price_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_status', models.CharField(default='Available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='tourism.serviceprovider')),
            ],
            options={
                'db_table': 'transportation_services',
            },
        ),
        migrations.CreateModel(
            name='TransportationImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='transportation/')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.transportation')),
            ],
            options={
                'db_table': 'transportation_images',
            },
        ),
    ]
