# Generated by Django 6.0.3 on 2026-08-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_alter_serviceprovider_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='available_times',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='price_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('available_times', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tourism.activity')),
            ],
            options={
                'db_table': 'activity_items',
            },
        ),
        migrations.CreateModel(
            name='ActivityItemImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='activity_items/')),
                ('activity_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.activityitem')),
            ],
            options={
                'db_table': 'activity_item_images',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_unit', models.CharField(default='/ day', max_length=50)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('availability_status', models.CharField(default='Available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tourism.transportation')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.vehicle')),
            ],
            options={
                'db_table': 'vehicle_images',
            },
        ),
    ]
