# Generated by Django 6.0.3 on 2026-08-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_destination_area_serviceprovider_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristprofile',
            name='previous_trips',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
