# Generated by Django 6.0.3 on 2026-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_touristprofile_previous_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('Waterfall', 'Waterfall'), ('Temple', 'Temple'), ('Wildlife', 'Wildlife'), ('Museum', 'Museum'), ('Backwaters', 'Backwaters'), ('Other', 'Other')], max_length=50),
        ),
    ]
