# Generated by Django 6.0.3 on 2026-08-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_booking_payment_method_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenSpot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('spot_type', models.CharField(choices=[('Waterfall', 'Waterfall'), ('Viewpoint', 'Viewpoint'), ('Temple', 'Temple'), ('Beach', 'Beach'), ('Nature Spot', 'Nature Spot'), ('Cave', 'Cave'), ('Trekking Trail', 'Trekking Trail'), ('Lake', 'Lake'), ('Heritage', 'Heritage'), ('Other', 'Other')], default='Nature Spot', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hidden_spots/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_spots', to='tourism.user')),
            ],
            options={
                'db_table': 'hidden_spots',
                'ordering': ['-created_at'],
            },
        ),
    ]
