# Generated by Django 6.0.3 on 2026-08-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_hiddenspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenSpotImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='hidden_spots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.hiddenspot')),
            ],
            options={
                'db_table': 'hidden_spot_images',
            },
        ),
    ]
