# Generated by Django 6.0.3 on 2026-09-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_hiddenspotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='checkin_otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='checkin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='checkin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='checkout_otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='checkout_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='checkout_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
